<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Knightage.Crm.Service</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Knightage.Crm.Core\Knightage.Crm.Core.csproj" />
  </ItemGroup>

</Project>
